### ISSUE TITLE
Broken image link

### ISSUE THREAD

**Issue by hilmanski** [WebCrateApp/webcrate#23] opened 2021-08-25 09:18 UTC
### 🏷️ WebCrate Version

v?

### ⚙️ Environment

Chrome

### 🐞 Describe the bug

image of a link is broken

### 📚 To Reproduce

I add a link via extension
in this case webcrate.app itself
when we click to preview this link

![Uploading Screen Shot 2021-08-25 at 5.16.01 PM.png…](https://i.ibb.co/HDCx9Rv/Screen-Shot-2021-08-25-at-5-16-01-PM.png)

### 💡 Expected behavior

image is not shown

**Comment by BetaHuhn** [comment] 2021-08-25 09:29
That's wierd, it doesn't show an image for me too.

I think the problem is on webcrate.app, it should work for most other links!

It's using another OSS library of mine ([metadata-scraper](https://github.com/BetaHuhn/metadata-scraper)) to retrieve the title, description and image for a link.

**Comment by BetaHuhn** [comment] 2021-08-25 09:45
Closing this for now, please reopen it if you find other links that don't work!

**Closed by BetaHuhn** 2021-08-25 09:45 UTC
Labels: bug
