### ISSUE TITLE
Can't add links in the mobile PWA version

### ISSUE THREAD

**Issue by hugohabicht01** [WebCrateApp/webcrate#34] opened 2021-09-11 15:17 UTC
### 🏷️ WebCrate Version

v1.0.2

### ⚙️ Environment

Mobile

### 🐞 Describe the bug

When I try adding a link it just says `Error: Network Error` instead of adding the link

### 📚 To Reproduce

Install the PWA version on Android and try adding a link

### 💡 Expected behavior

Should just add a link to the webcrate

**Comment by BetaHuhn** [comment] 2021-09-11 15:21
The latest version of WebCrate is `v1.2.0` and you appear to be on `v1.0.2`. Please update to the latest version and report back if the issue is still occurring. Check out the [documentation](https://webcrate.app/docs/faq#how-are-updates-handled) on how you can update WebCrate.

**Comment by BetaHuhn** [comment] 2021-09-13 12:21
Closing this for now. Please reopen it if the issue still occurs after you update to the latest version.

**Closed by BetaHuhn** 2021-09-13 12:21 UTC
Labels: bug
